// <auto-generated />
using BlazorApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlazorApp.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Elm St",
                            City = "Metropolis",
                            CompanyName = "Acme Corp",
                            ContactName = "John Doe",
                            Country = "USA",
                            Phone = "555-1234",
                            PostalCode = "12345",
                            Region = "NA"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak St",
                            City = "Springfield",
                            CompanyName = "Globex Inc",
                            ContactName = "Jane Smith",
                            Country = "USA",
                            Phone = "555-5678",
                            PostalCode = "67890",
                            Region = "NA"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine St",
                            City = "Capital City",
                            CompanyName = "Initech",
                            ContactName = "Bill Lumbergh",
                            Country = "USA",
                            Phone = "555-9012",
                            PostalCode = "11223",
                            Region = "NA"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Maple St",
                            City = "Raccoon City",
                            CompanyName = "Umbrella Corp",
                            ContactName = "Alice Abernathy",
                            Country = "USA",
                            Phone = "555-3456",
                            PostalCode = "44556",
                            Region = "NA"
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Cedar St",
                            City = "Gotham",
                            CompanyName = "Wayne Enterprises",
                            ContactName = "Bruce Wayne",
                            Country = "USA",
                            Phone = "555-7890",
                            PostalCode = "77889",
                            Region = "NA"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
